import type { APIGatewayProxyEventV2, APIGatewayProxyResultV2 } from 'aws-lambda';

export type ApiEvent = APIGatewayProxyEventV2;
export type ApiResult = APIGatewayProxyResultV2;
export type RouteHandler = (event: ApiEvent) => Promise<ApiResult>;

export interface RegisterBody {
  inviteCode: string;
  username: string;
  email: string;
  /** PEM-encoded RSA public key generated on-device. */
  publicKey: string;
  /** Private key wrapped with the Argon2id-derived KEK (base64). */
  encryptedPrivateKey: string;
  /** Random salt used for the Argon2id KDF (base64). */
  argon2Salt: string;
  /** Cognito password (also used on-device to derive the Argon2 KEK). */
  password: string;
}

export interface FlagsBody {
  read?: boolean;
  /** ID of the folder to move the email into (resolved to a name via config table). */
  folderId?: string;
  /** Full replacement set of label IDs to apply to the email. */
  labelIds?: string[];
  /** Client's current version for optimistic locking. */
  version?: number;
}

export interface SendEmailBody {
  /** Client-generated email ULID — identifies the draft blobs already saved in S3. */
  emailId:  string;
  /**
   * Raw 32-byte AES-256 emailKey, base64-encoded.
   * The server uses this to decrypt the draft blobs from S3 and build the outgoing MIME.
   */
  emailKey: string;
}

export interface PushSubscribeBody {
  /** Random UUID generated by the client; stored in localStorage so the client can update/remove its record. */
  deviceId: string;
  /** Web Push subscription endpoint URL. */
  endpoint: string;
  /** P-256 DH public key (base64url). */
  p256dh: string;
  /** Authentication secret (base64url). */
  auth: string;
}

export interface Label {
  /** Short random base64url string (9 bytes) generated on the client. */
  id: string;
  /** User-defined label name. */
  name: string;
  /** User-defined color for the label (hex color code). */
  color: string;
}

